# Generated by Django 6.0.7 on 2026-08-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_steps", "0001_initial"),
        ("approval_workflows", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("employees", "0006_employee_supervisor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_object_id", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_approval_instances",
                        to="approval_steps.approvalstep",
                    ),
                ),
                (
                    "request_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empoyee_approval_instances",
                        to="employees.employee",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_instances",
                        to="approval_workflows.approvalworkflow",
                    ),
                ),
            ],
        ),
    ]
