# Generated by Django 6.0.7 on 2026-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_instances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_PROGRESS", "In Progress"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ]
            ),
        ),
    ]
