# Generated by Django 6.0.7 on 2026-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_instances", "0002_alter_approvalinstance_status"),
        ("approval_steps", "0001_initial"),
        ("approval_workflows", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("employees", "0006_employee_supervisor"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["request_content_type", "request_object_id"],
                name="approval_in_request_25db3e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalinstance",
            constraint=models.UniqueConstraint(
                fields=("request_content_type", "request_object_id"),
                name="unique_approval_per_request_object",
            ),
        ),
    ]
