# Generated by Django 6.0.7 on 2026-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "approval_instances",
            "0003_approvalinstance_approval_in_request_25db3e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_PROGRESS", "In Progress"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="IN_PROGRESS",
            ),
        ),
    ]
