# Generated by Django 6.0.7 on 2026-08-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_workflows", "0001_initial"),
        ("departments", "0002_initial"),
        ("employees", "0006_employee_supervisor"),
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_SUPERVISOR", "Direct Supervisor"),
                            ("SUPERVISOR_LEVEL", "Supervisor Level"),
                            ("ROLE", "Role"),
                            ("DEPARTMENT_ROLE", "Department Role"),
                            ("SPECIFIC_EMPLOYEE", "Specific Employee"),
                        ],
                        max_length=255,
                    ),
                ),
                ("supervisor_level", models.IntegerField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("can_skip", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_approval_steps",
                        to="departments.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_approval_steps",
                        to="employees.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position_approval_steps",
                        to="positions.employeeposition",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="approval_workflows.approvalworkflow",
                    ),
                ),
            ],
        ),
    ]
