# Generated by Django 6.0.7 on 2026-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Schedule"),
                            ("FLEX_DAILY", "Flexible Daily Hours"),
                            ("FLEX_WEEKLY", "Flexible Weekly Hours"),
                        ],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "required_hours_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "required_hours_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("break_minutes", models.PositiveSmallIntegerField(default=60)),
                ("grace_period_minute", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_ate", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
