# Generated by Django 6.0.7 on 2026-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeshift",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
