# Generated by Django 6.0.7 on 2026-07-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee_dayoffs", "0001_initial"),
        ("employee_shift_assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedayoff",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days_off",
                to="employee_shift_assignments.employeeshiftassignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeedayoff",
            constraint=models.UniqueConstraint(
                fields=("assignment", "day_of_week"),
                name="unique_day_off_per_assignment",
            ),
        ),
    ]
