# Generated by Django 6.0.7 on 2026-07-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leave_created_at_leave_updated_at_alter_leave_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave",
            old_name="approved_bv",
            new_name="approved_by",
        ),
    ]
