# Generated by Django 6.0.7 on 2026-08-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0003_rename_approved_bv_leave_approved_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="status",
        ),
    ]
