# Generated by Django 6.0.7 on 2026-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                ],
                default="present",
                max_length=20,
            ),
        ),
    ]
