# Generated by Django 6.0.7 on 2026-08-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_shift_assignments", "0001_initial"),
        ("employees", "0006_employee_supervisor"),
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeshiftassignment",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_assignments",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeeshiftassignment",
            name="shift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_assignments",
                to="shifts.employeeshift",
            ),
        ),
    ]
