# Generated by Django 6.0.7 on 2026-07-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_shift_assignments", "0001_initial"),
        ("employees", "0002_alter_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_employees",
                to="employee_shift_assignments.employeeshiftassignment",
            ),
        ),
    ]
