# Generated by Django 6.0.7 on 2026-07-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="shift_assignment",
        ),
    ]
