# Generated by Django 6.0.7 on 2026-08-01 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_remove_employee_shift_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="employees.employee",
            ),
        ),
    ]
